apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-deployment
  namespace: echoserver-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
spec:
  selector:
    app: echoserver
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP