apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/matiasg1200/test.git
    targetRevision: HEAD
    path: kubernetes/manifests/echoserver-application/
  destination:
    server: https://kubernetes.default.svc
    namespace: echoserver
  syncPolicy:
    automated:
      selfHeal: true